version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/pokedex
      SPRING_DATASOURCE_USERNAME: brookmulu
      SPRING_DATASOURCE_PASSWORD: liomessi10
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: pokedex-db-dev
    environment:
      POSTGRES_USER: brookmulu
      POSTGRES_PASSWORD: liomessi10
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
